apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-appln
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ./helm-chart
    repoURL: 'https://github.com/meeran2019/argo-cd.git'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true