apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-demo
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-charts/webapp-nginx
    repoURL: 'https://github.com/meeran2019/helm-tutorial.git'
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
      values: ''
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true